import mongoose from 'mongoose';
import {
  PAYMENT_METHODS,
  RETURN_STATUS,
  SETTLEMENT_DIRECTIONS,
} from '../config/constants.js';

// One returned physical unit. Snapshots mirror the original bill item so the
// return record stays accurate even if the product is later edited/deleted.
const returnItemSchema = new mongoose.Schema(
  {
    // The ORIGINAL unit being returned (its barcode is retired -> 'returned').
    barcode: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Barcode',
      required: true,
    },
    product: { type: mongoose.Schema.Types.ObjectId, ref: 'Product' },
    productName: { type: String, required: true },
    articleNumber: { type: String },
    size: { type: String },
    mrp: { type: Number, required: true }, // original line price (snapshot)
    // Effective amount actually paid for this unit on the original bill, i.e.
    // its MRP share of the bill total after discount/tax:
    //   round(bill.total * mrp / bill.subtotal)
    refundAmount: { type: Number, required: true, min: 0 },
    // true  -> unit goes back into sellable stock and a fresh label is minted;
    // false -> unit is retired (damaged), not restocked.
    resellable: { type: Boolean, default: true },
    // The freshly minted replacement barcode (only for resellable returns — the
    // original label may have been lost, so a new one is generated & re-printable).
    newBarcode: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Barcode',
      default: null,
    },
  },
  { _id: false }
);

// Real money moved to settle a refund-out (the collect side lives on the
// exchange bill's payments, so cash is never double-counted).
const settlementPaymentSchema = new mongoose.Schema(
  {
    method: { type: String, enum: PAYMENT_METHODS, required: true },
    amount: { type: Number, required: true, min: 0 },
    reference: { type: String, trim: true },
  },
  { _id: false }
);

// A sales return / exchange ("credit note"). Created atomically: it retires the
// returned units, optionally mints replacements, optionally creates a new sale
// bill for exchanged-in items, and records how the net settled.
const returnSchema = new mongoose.Schema(
  {
    // Human-readable reference (counter-backed), e.g. "RET-000001".
    returnNumber: { type: String, default: null },
    originalBill: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Bill',
      required: true,
    },
    originalBillNumber: { type: String, trim: true }, // snapshot
    customer: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Customer',
      default: null,
    },
    customerName: { type: String, trim: true },
    customerPhone: { type: String, trim: true },
    items: {
      type: [returnItemSchema],
      validate: {
        validator: (arr) => Array.isArray(arr) && arr.length > 0,
        message: 'A return must have at least one item',
      },
    },
    // Total credit generated by the returned goods (Σ items.refundAmount).
    refundTotal: { type: Number, required: true, min: 0 },
    // ---- exchange (optional new purchase settled against this return) ----
    exchangeBill: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Bill',
      default: null,
    },
    exchangeTotal: { type: Number, default: 0, min: 0 }, // new bill total (0 if none)
    // exchangeTotal - refundTotal. > 0 => customer pays; < 0 => shop refunds.
    netAmount: { type: Number, default: 0 },
    settlement: {
      direction: { type: String, enum: SETTLEMENT_DIRECTIONS, default: 'even' },
      amount: { type: Number, default: 0, min: 0 }, // |netAmount|
      payments: { type: [settlementPaymentSchema], default: [] }, // refund-out only
    },
    remarks: { type: String, trim: true },
    status: { type: String, enum: RETURN_STATUS, default: 'completed' },
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
  },
  { timestamps: true }
);

// returnNumber is unique only across records that actually have one.
returnSchema.index(
  { returnNumber: 1 },
  { unique: true, partialFilterExpression: { returnNumber: { $type: 'string' } } }
);

// Drives returns history (newest first) and per-bill return lookups.
returnSchema.index({ createdAt: -1 });
returnSchema.index({ originalBill: 1 });

const Return = mongoose.model('Return', returnSchema);

export default Return;
